[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'roxma/nvim-yarp'
if = '!has("nvim")'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = '!has("nvim")'

# filer
[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'scrooloose/nerdtree'

# mode line
[[plugins]]
repo = 'itchyny/lightline.vim'

# syntax checker
[[plugins]]
repo = 'scrooloose/syntastic'

# editor-config
[[plugins]]
repo = 'sgur/vim-editorconfig'

# color theme
[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'freeo/vim-kalisi'

[[plugins]]
repo = 'aereal/vim-colors-japanesque'

# fuzzy finder
[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
command! -bang -nargs=* Ag
  \ call fzf#vim#ag(<q-args>,
  \                 <bang>0 ? fzf#vim#with_preview('up:60%')
  \                         : fzf#vim#with_preview('right:50%:hidden', '?'),
  \                 <bang>0)
'''
