;;; cnf-colors.el --- thesaitama Emacs configuration

;;; Commentary:
;;
;; This file is part of thesaitam Emacs configuration

;;; Code:

;; ------------------------------------------------------------------------
;; color (custom set face)

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(region ((t (:background "Gray40"))))
 '(tool-bar ((t (:foreground "cyan"))))
 '(minibuffer-prompt ((t (:foreground "blue"))))
 '(fringe ((t (:background "Gray12" :foreground "blue"))))
 '(isearch ((t (:background "LightPink" :foreground "black"))))
 '(isearch-lazy-highlight-face ((t (:background "LightCyan" :foreground "black"))))
 '(bm-face ((t (:background "color-28"))))
 '(bm-fringe-face ((t (:background "color-28"))))
 '(diff-added ((((type tty)) (:foreground "green"))))
 '(diff-removed ((((type tty)) (:foreground "red"))))
 '(dired-header ((t (:background "BrightBlue" :foreground "white"))))
 '(rainbow-delimiters-unmatched-face ((t (:background "red" :foreground "white"))))
 '(rainbow-delimiters-mismatched-face ((t (:background "red" :foreground "white"))))
 '(dired-subtree-depth-1-face ((t (:background "Gray19"))))
 '(dired-subtree-depth-2-face ((t (:background "Gray20"))))
 '(dired-subtree-depth-3-face ((t (:background "Gray21"))))
 '(dired-subtree-depth-4-face ((t (:background "Gray22"))))
 '(dired-subtree-depth-5-face ((t (:background "Gray23"))))
 '(dired-subtree-depth-6-face ((t (:background "Gray24"))))
 '(elscreen-tab-background-face ((t (:background "Gray10" :foreground "Gray90"))))
 '(elscreen-tab-control-face ((t (:background "Gray20" :foreground "Gray90"))))
 '(elscreen-tab-current-screen-face ((t (:background "Gray80" :foreground "Gray20"))))
 '(elscreen-tab-other-screen-face ((t (:background "Gray25" :foreground "Gray80"))))
 '(font-lock-doc-face ((t (:foreground "green"))))
 '(helm-buffer-file ((t (:inherit font-lock-builtin-face :foreground "white"))))
 '(helm-buffer-process ((t (:inherit font-lock-builtin-face :foreground "magenta"))))
 '(helm-ff-directory ((t (:background "Gray25" :foreground "orange"))))
 '(helm-ff-dotted-directory ((t (:background "glay" :foreground "white"))))
 '(helm-ff-executable ((t (:inherit font-lock-builtin-face :foreground "cyan"))))
 '(helm-ff-file ((t (:inherit font-lock-builtin-face :foreground "white"))))
 '(helm-ff-symlink ((t (:inherit font-lock-builtin-face :foreground "magenta"))))
 '(helm-match ((t (:foreground "cyan"))))
 '(helm-selection ((t (:background "Gray30"))))
 '(helm-source-header ((t (:background "BrightBlue" :foreground "white"))))
 '(highlight-symbol-face ((t (:background "Gray25"))))
 '(hl-line ((t (:background "color-236"))))
 '(holiday ((t (:background "pink"))))
 '(japanese-holiday-saturday ((t (:background "cyan"))))
 '(link ((t (:foreground "blue"))))
 '(linum ((t (:inherit (shadow default) :background "Gray22"))))
 '(magit-branch-local ((t (:foreground "magenta"))))
 '(magit-branch-remote ((t (:foreground "blue"))))
 '(magit-context-highlight ((t (:background "Gray23"))))
 '(magit-diff-added ((((type tty)) (:foreground "green"))))
 '(magit-diff-added-highlight ((((type tty)) (:foreground "LimeGreen"))))
 '(magit-diff-context-highlight ((t (:background "Gray23"))))
 '(magit-diff-file-heading ((((type tty)) nil)))
 '(magit-diff-removed ((((type tty)) (:foreground "red"))))
 '(magit-diff-removed-highlight ((((type tty)) (:foreground "IndianRed"))))
 '(magit-log-author ((t (:foreground "magenta"))))
 '(magit-section-highlight ((t (:background "Gray23"))))
 '(outline-1 ((t (:background "BrightBlue" :foreground "white"))))
 '(outline-2 ((t (:foreground "cyan"))))
 '(outline-3 ((t (:foreground "blue"))))
 '(outline-4 ((t (:foreground "goldenrod"))))
 '(markdown-header-delimiter-face ((t (:inherit org-mode-line-clock))))
 '(markdown-header-face-1 ((t (:inherit outline-1 :weight bold))))
 '(markdown-header-face-2 ((t (:inherit outline-2 :weight bold))))
 '(markdown-header-face-3 ((t (:inherit outline-3 :weight bold))))
 '(markdown-header-face-4 ((t (:inherit outline-4 :weight bold))))
 '(markdown-header-face-5 ((t (:inherit outline-5 :weight bold))))
 '(markdown-header-face-6 ((t (:inherit outline-6 :weight bold))))
 '(markdown-pre-face ((t (:foreground "ivory"))))
 '(neo-dir-link-face ((t (:background "Gray25" :foreground "orange"))))
 '(neo-file-link-face ((t (:foreground "ivory"))))
 '(neo-header-face ((t (:foreground "white"))))
 '(neo-root-dir-face ((t (:background "BrightBlue" :foreground "white"))))
 '(neo-vc-default-face ((t (:foreground "ivory"))))
 '(neo-vc-edited-face ((t (:foreground "green"))))
 '(neo-vc-removed-face ((t (:foreground "red"))))
 '(neo-vc-up-to-date-face ((t (:foreground "ivory"))))
 '(package-name ((t (:foreground "blue"))))
 '(web-mode-comment-face ((t (:foreground "green"))))
 '(web-mode-css-at-rule-face ((t (:foreground "magenta"))))
 '(web-mode-css-pseudo-class ((t (:foreground "blue"))))
 '(web-mode-css-selector-face ((t (:foreground "blue"))))
 '(web-mode-doctype-face ((t (:foreground "glay"))))
 '(web-mode-html-attr-equal-face ((t (:foreground "white"))))
 '(web-mode-html-attr-name-face ((t (:foreground "LightBlue"))))
 '(web-mode-html-attr-value-face ((t (:foreground "yellow"))))
 '(web-mode-html-tag-face ((t (:foreground "cyan"))))
 '(web-mode-server-comment-face ((t (:foreground "green"))))
 '(which-func ((t (:foreground "ivory"))))
 '(which-key-command-description-face ((t (:foreground "white")))))

;; ------------------------------------------------------------------------

(provide 'cnf-colors.el)
;;; cnf-colors.el ends here
